{% from "alertmanager/alertmanager.map" import alertmanager with context %}
global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: {{ alertmanager.smtp_smarthost }}
  smtp_from: {{ alertmanager.smtp_from }}
  {% if alertmanager.smtp_auth_username is defined %}
  smtp_auth_username: {{ alertmanager.smtp_auth_username }}
  {% endif %}
  {% if alertmanager.smtp_auth_password is defined %}
  smtp_auth_password: {{ alertmanager.smtp_auth_password }}
  {% endif %}
  smtp_require_tls: {{ alertmanager.smtp_require_tls }}

# The directory from which notification templates are read.
templates: 
- '/etc/alertmanager/template/*.tmpl'

# The root route on which each incoming alert enters.
{{ alertmanager.config|yaml(False) }}
